-- Create budgets table
CREATE TABLE budgets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  max_amount NUMERIC NOT NULL,
  payment_type_id BIGINT NOT NULL REFERENCES payment_types(id),
  category_id BIGINT REFERENCES expense_categories(id),
  period VARCHAR(10) NOT NULL CHECK (period IN ('weekly', 'monthly', 'yearly')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(payment_type_id, category_id, period)
);

-- Create trigger for updated_at column (if not already created)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to budgets table
CREATE TRIGGER update_budgets_updated_at BEFORE UPDATE ON budgets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
