-- Migration: Create Expense Tags and Mappings
-- Description: Creates expense_tags table for tag definitions and expense_tag_mappings junction table for many-to-many relationship

-- Create expense_tags table
CREATE TABLE expense_tags (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#71717a',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create junction table for many-to-many relationship
CREATE TABLE expense_tag_mappings (
  expense_id BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES expense_tags(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (expense_id, tag_id)
);

-- Create indexes for better query performance
CREATE INDEX idx_expense_tags_user_id ON expense_tags(user_id);
CREATE INDEX idx_expense_tag_mappings_expense_id ON expense_tag_mappings(expense_id);
CREATE INDEX idx_expense_tag_mappings_tag_id ON expense_tag_mappings(tag_id);

-- Create unique index for case-insensitive tag names per user
CREATE UNIQUE INDEX unique_tag_name_per_user ON expense_tags(user_id, LOWER(name));

-- Enable Row Level Security
ALTER TABLE expense_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_tag_mappings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for expense_tags
-- Users can only see their own tags
CREATE POLICY "Users can view their own tags"
  ON expense_tags FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own tags
CREATE POLICY "Users can create their own tags"
  ON expense_tags FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own tags
CREATE POLICY "Users can update their own tags"
  ON expense_tags FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own tags
CREATE POLICY "Users can delete their own tags"
  ON expense_tags FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for expense_tag_mappings
-- Users can view mappings for their own expenses
CREATE POLICY "Users can view their own expense tag mappings"
  ON expense_tag_mappings FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM expenses 
      WHERE expenses.id = expense_tag_mappings.expense_id
    )
  );

-- Users can create mappings for their own expenses
CREATE POLICY "Users can create mappings for their own expenses"
  ON expense_tag_mappings FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM expenses 
      WHERE expenses.id = expense_tag_mappings.expense_id
    )
  );

-- Users can delete mappings for their own expenses
CREATE POLICY "Users can delete mappings for their own expenses"
  ON expense_tag_mappings FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM expenses 
      WHERE expenses.id = expense_tag_mappings.expense_id
    )
  );

-- Add comment for documentation
COMMENT ON TABLE expense_tags IS 'Stores user-defined tags for expense categorization';
COMMENT ON TABLE expense_tag_mappings IS 'Junction table for many-to-many relationship between expenses and tags';
