-- Migration: Create Investment Transactions and Price Tracking
-- Description: Creates investment_transactions table for tracking stock purchases/sales and investment_current_prices for caching real-time prices

-- Create transaction type enum
CREATE TYPE transaction_type AS ENUM ('BUY', 'SELL');

-- Create investment_transactions table
CREATE TABLE investment_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  ticker VARCHAR(20) NOT NULL,
  quantity DECIMAL(15, 6) NOT NULL CHECK (quantity > 0),
  purchase_price DECIMAL(15, 4) NOT NULL CHECK (purchase_price >= 0),
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  transaction_type transaction_type NOT NULL DEFAULT 'BUY',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create investment_current_prices table for caching Yahoo Finance data
CREATE TABLE investment_current_prices (
  ticker VARCHAR(20) PRIMARY KEY,
  price DECIMAL(15, 4) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  exchange_name VARCHAR(50),
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_investment_transactions_user_id ON investment_transactions(user_id);
CREATE INDEX idx_investment_transactions_ticker ON investment_transactions(ticker);
CREATE INDEX idx_investment_transactions_date ON investment_transactions(transaction_date DESC);
CREATE INDEX idx_investment_transactions_user_ticker ON investment_transactions(user_id, ticker);
CREATE INDEX idx_investment_current_prices_last_updated ON investment_current_prices(last_updated);

-- Enable Row Level Security
ALTER TABLE investment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE investment_current_prices ENABLE ROW LEVEL SECURITY;

-- RLS Policies for investment_transactions
-- Users can only view their own transactions
CREATE POLICY "Users can view their own transactions"
  ON investment_transactions FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own transactions
CREATE POLICY "Users can create their own transactions"
  ON investment_transactions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own transactions
CREATE POLICY "Users can update their own transactions"
  ON investment_transactions FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own transactions
CREATE POLICY "Users can delete their own transactions"
  ON investment_transactions FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for investment_current_prices
-- All authenticated users can read current prices (shared cache)
CREATE POLICY "Authenticated users can view current prices"
  ON investment_current_prices FOR SELECT
  TO authenticated
  USING (true);

-- Only service role can insert/update prices (for API calls)
CREATE POLICY "Service role can insert prices"
  ON investment_current_prices FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Service role can update prices"
  ON investment_current_prices FOR UPDATE
  TO authenticated
  USING (true);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_investment_transaction_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER trigger_update_investment_transaction_timestamp
  BEFORE UPDATE ON investment_transactions
  FOR EACH ROW
  EXECUTE FUNCTION update_investment_transaction_updated_at();

-- Add comments for documentation
COMMENT ON TABLE investment_transactions IS 'Stores user stock purchase and sale transactions';
COMMENT ON TABLE investment_current_prices IS 'Caches current stock prices from Yahoo Finance API to minimize API calls';
COMMENT ON TYPE transaction_type IS 'Type of investment transaction: BUY or SELL';
