-- Migration 011: Create Payment Type Balance History Table
-- Purpose: Store weekly snapshots of payment type balances for historical tracking
-- Author: System
-- Date: 2025-12-27

-- Create the balance history table
CREATE TABLE IF NOT EXISTS payment_type_balance_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_type_id BIGINT NOT NULL REFERENCES payment_types(id) ON DELETE CASCADE,
  balance NUMERIC NOT NULL DEFAULT 0,
  snapshot_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_balance_history_payment_type 
  ON payment_type_balance_history(payment_type_id);

CREATE INDEX IF NOT EXISTS idx_balance_history_date 
  ON payment_type_balance_history(snapshot_date DESC);

-- Unique constraint to prevent duplicate snapshots for same payment type on same date
CREATE UNIQUE INDEX IF NOT EXISTS idx_balance_history_unique 
  ON payment_type_balance_history(payment_type_id, snapshot_date);

-- Add comment to table
COMMENT ON TABLE payment_type_balance_history IS 'Stores weekly snapshots of payment type balances for historical analysis';

-- Insert initial snapshot with current balances
-- This populates the history table with today's balances as a starting point
INSERT INTO payment_type_balance_history (payment_type_id, balance, snapshot_date)
SELECT id, COALESCE(current_balance, 0), CURRENT_DATE
FROM payment_types
ON CONFLICT (payment_type_id, snapshot_date) DO NOTHING;
