-- Migration 012: Create Email Reports Log Table
-- Purpose: Track history of sent email reports for audit and troubleshooting
-- Author: System
-- Date: 2025-12-28

-- Create the email reports log table
CREATE TABLE IF NOT EXISTS email_reports_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  report_type VARCHAR(50) NOT NULL, -- 'monthly', 'weekly', 'quarterly', etc.
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  recipient_email VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL, -- 'sent', 'failed', 'pending'
  period_start DATE,
  period_end DATE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  error_message TEXT,
  email_id VARCHAR(255), -- External email service ID (e.g., Resend)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_reports_log_sent_at 
  ON email_reports_log(sent_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_reports_log_recipient 
  ON email_reports_log(recipient_email);

CREATE INDEX IF NOT EXISTS idx_email_reports_log_user_id 
  ON email_reports_log(user_id);

CREATE INDEX IF NOT EXISTS idx_email_reports_log_status 
  ON email_reports_log(status);

CREATE INDEX IF NOT EXISTS idx_email_reports_log_report_type 
  ON email_reports_log(report_type);

-- Add comment to table
COMMENT ON TABLE email_reports_log IS 'Audit log for email reports sent to users';

-- Enable Row Level Security (RLS)
ALTER TABLE email_reports_log ENABLE ROW LEVEL SECURITY;

-- Create policy for users to view their own email reports
CREATE POLICY "Users can view their own email reports"
  ON email_reports_log
  FOR SELECT
  USING (auth.uid() = user_id);

-- Create policy for service role to insert/update (used by Edge Functions)
CREATE POLICY "Service role can insert email reports"
  ON email_reports_log
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update email reports"
  ON email_reports_log
  FOR UPDATE
  USING (true);
